apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  containers:
  - name: psql-client-container
    image: bitnami/postgresql:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
  restartPolicy: Never

