---
- name: Ensure Python pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: yes  # Use if the playbook requires elevated privileges

- name: Ensure packaging module is installed using Python command
  ansible.builtin.command:
    cmd: pip install packaging
  changed_when: false

- name: Ensure kubernetes module is installed using Python command
  ansible.builtin.command:
    cmd: pip install kubernetes
  changed_when: false
